
version: '3.9'
services:
  bot:
    build:
      context: .
      dockerfile: ./docker/bot/Dockerfile
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/create_table.sql:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci